[package]
name = "veilocity_circuits"
type = "bin"
authors = ["Veilocity Team"]

[dependencies]
# Poseidon hash library (BN254 compatible)
poseidon = { tag = "v0.1.1", git = "https://github.com/noir-lang/poseidon" }
